services:
  postgres:
    image: postgres:17
    container_name: smart-services-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-toturHub}
      POSTGRES_USER: ${DB_USERNAME:-neondb_owner}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-npg_UpsgQvfbt87d}
    ports:
      - "5432"   # Host:Container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-neondb_owner} -d ${DB_NAME:-toturHub}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - smart-network

  rental:
    build: .
    container_name: smart-services-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"   # Host:Container
    env_file:
      - .env
    environment:
      # Database
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-toturHub}
      DB_USERNAME: ${DB_USERNAME:-neondb_owner}
      DB_PASSWORD: ${DB_PASSWORD:-npg_UpsgQvfbt87d}
      DB_SSLMODE: require # NEON REQUIRES SSL

      # JWT
      JWT_SECRET: ${JWT_SECRET:-MySuperSecretKeyWith64+CharactersForDevOnly1234567890!}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}

      # Spring profiles & file uploads
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      FILE_UPLOAD_DIR: ${FILE_UPLOAD_DIR:-uploads}

      # Swagger / OpenAPI
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui/index.html
    volumes:
      - ./uploads:/app/uploads
    networks:
      - smart-network

volumes:
  postgres_data:

networks:
  smart-network:
    driver: bridge